In [1]:
# importing pandas and regex

import pandas as pd
import re

In [2]:
# importing os and grabbing cwd

import os

cwd = os.getcwd()

cwd

'C:\\Users\\CharlesYi\\Jupyter Notebook\\Alteryx Challenges\\Challenge 224_Mushroom for Improvement'

In [3]:
# joining path with file name

path = os.path.join(cwd, 'mushrooms.xlsx')

# grabbing mushroom data

df_mushrooms = pd.read_excel(path)

df_mushrooms.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [4]:
# grabbing attribute data

df_attribute = pd.read_excel(path, sheet_name = 'Sheet2')

df_attribute.head()

                                              Field1
0  Attribute Information: (classes: edible=e, poi...
1  cap-shape: bell=b,conical=c,convex=x,flat=f, k...
2  cap-surface: fibrous=f,grooves=g,scaly=y,smooth=s
3  cap-color: brown=n,buff=b,cinnamon=c,gray=g,gr...
4                            bruises: bruises=t,no=f

In [5]:
# adding record id to mushrooms data

df_mushrooms['recordid'] = range(1, len(df_mushrooms) + 1)

df_mushrooms.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat,recordid
0,p,x,s,n,t,p,f,c,n,k,...,w,w,p,w,o,p,k,s,u,1
1,e,x,s,y,t,a,f,c,b,k,...,w,w,p,w,o,p,n,n,g,2
2,e,b,s,w,t,l,f,c,b,n,...,w,w,p,w,o,p,n,n,m,3
3,p,x,y,w,t,p,f,c,n,n,...,w,w,p,w,o,p,k,s,u,4
4,e,x,s,g,f,n,f,w,b,k,...,w,w,p,w,o,e,n,a,g,5

In [6]:
# transposing

# selecting columns to pivot

pivot_cols = df_mushrooms.columns[0:23]

df_mushrooms_pivot = pd.melt(df_mushrooms, id_vars = ['recordid'], value_vars = pivot_cols)

df_mushrooms_pivot.head()

   recordid variable value
0         1    class     p
1         2    class     e
2         3    class     e
3         4    class     p
4         5    class     e

In [7]:
# concating name and value

df_mushrooms_pivot['category-value'] = df_mushrooms_pivot['variable']+' '+(df_mushrooms_pivot['value'])

df_mushrooms_pivot.head()

   recordid variable value category-value
0         1    class     p        class p
1         2    class     e        class e
2         3    class     e        class e
3         4    class     p        class p
4         5    class     e        class e

In [8]:
# trimming attribute Field1

df_attribute['Field1'] = df_attribute['Field1'].str.strip()

df_attribute.head()

                                              Field1
0  Attribute Information: (classes: edible=e, poi...
1  cap-shape: bell=b,conical=c,convex=x,flat=f, k...
2  cap-surface: fibrous=f,grooves=g,scaly=y,smooth=s
3  cap-color: brown=n,buff=b,cinnamon=c,gray=g,gr...
4                            bruises: bruises=t,no=f

In [9]:
# replacing attribute information in first row 


df_attribute['Field1'] = df_attribute['Field1'].str.replace('Attribute Information: ', '')

df_attribute.head()

                                              Field1
0                   (classes: edible=e, poisonous=p)
1  cap-shape: bell=b,conical=c,convex=x,flat=f, k...
2  cap-surface: fibrous=f,grooves=g,scaly=y,smooth=s
3  cap-color: brown=n,buff=b,cinnamon=c,gray=g,gr...
4                            bruises: bruises=t,no=f

In [10]:
# replacing '(' and ')'

df_attribute['Field1'] = df_attribute['Field1'].apply(lambda x: re.sub(r'[()]', '', x))

df_attribute.head()

                                              Field1
0                     classes: edible=e, poisonous=p
1  cap-shape: bell=b,conical=c,convex=x,flat=f, k...
2  cap-surface: fibrous=f,grooves=g,scaly=y,smooth=s
3  cap-color: brown=n,buff=b,cinnamon=c,gray=g,gr...
4                            bruises: bruises=t,no=f

In [11]:
# splitting field to separate columns

# using just str split func with expand

# df_attribute['Field1'].str.split(r'[:()]+', expand=True)

# using lambda with re.split and pd.Series

df_attribute[['category', 'value']]= df_attribute['Field1'].apply(lambda x: pd.Series(re.split(r'[:]', x)))
df_attribute.head()

,Field1,category,value
0,"classes: edible=e, poisonous=p",classes,"edible=e, poisonous=p"
1,"cap-shape: bell=b,conical=c,convex=x,flat=f, k...",cap-shape,"bell=b,conical=c,convex=x,flat=f, knobbed=k,s..."
2,"cap-surface: fibrous=f,grooves=g,scaly=y,smooth=s",cap-surface,"fibrous=f,grooves=g,scaly=y,smooth=s"
3,"cap-color: brown=n,buff=b,cinnamon=c,gray=g,gr...",cap-color,"brown=n,buff=b,cinnamon=c,gray=g,green=r,pink..."
4,"bruises: bruises=t,no=f",bruises,"bruises=t,no=f"

In [12]:
# tokenizing value into rows

df_attribute['value'] = df_attribute['value'].str.split(',')

In [13]:
df_attribute.head()

,Field1,category,value
0,"classes: edible=e, poisonous=p",classes,"[ edible=e, poisonous=p]"
1,"cap-shape: bell=b,conical=c,convex=x,flat=f, k...",cap-shape,"[ bell=b, conical=c, convex=x, flat=f, knobbe..."
2,"cap-surface: fibrous=f,grooves=g,scaly=y,smooth=s",cap-surface,"[ fibrous=f, grooves=g, scaly=y, smooth=s]"
3,"cap-color: brown=n,buff=b,cinnamon=c,gray=g,gr...",cap-color,"[ brown=n, buff=b, cinnamon=c, gray=g, green=r..."
4,"bruises: bruises=t,no=f",bruises,"[ bruises=t, no=f]"

In [18]:
# exploding into rows

df_attribute = df_attribute.explode('value')

df_attribute.head()

                                              Field1   category         value
0                     classes: edible=e, poisonous=p    classes      edible=e
0                     classes: edible=e, poisonous=p    classes   poisonous=p
1  cap-shape: bell=b,conical=c,convex=x,flat=f, k...  cap-shape        bell=b
1  cap-shape: bell=b,conical=c,convex=x,flat=f, k...  cap-shape     conical=c
1  cap-shape: bell=b,conical=c,convex=x,flat=f, k...  cap-shape      convex=x

In [21]:
# splitting value into two columns

# method 1

df_attribute[['value_header', 'value_code']] = df_attribute['value'].str.split('=', expand = True)

df_attribute.head()

,Field1,category,value,value_header,value_code
0,"classes: edible=e, poisonous=p",classes,edible=e,edible,e
0,"classes: edible=e, poisonous=p",classes,poisonous=p,poisonous,p
1,"cap-shape: bell=b,conical=c,convex=x,flat=f, k...",cap-shape,bell=b,bell,b
1,"cap-shape: bell=b,conical=c,convex=x,flat=f, k...",cap-shape,conical=c,conical,c
1,"cap-shape: bell=b,conical=c,convex=x,flat=f, k...",cap-shape,convex=x,convex,x

In [24]:
# method 2

df_attribute['value'].apply(lambda x: pd.Series(re.split('=', x)))

             0  1
0       edible  e
0    poisonous  p
1         bell  b
1      conical  c
1       convex  x
..         ... ..
22     meadows  m
22       paths  p
22       urban  u
22       waste  w
22       woods  d

[128 rows x 2 columns]

In [26]:
# adjusting 'classes' category to class

df_attribute['category'] = df_attribute['category'].apply(lambda x: x if x != 'classes' else 'class')

df_attribute.head()

,Field1,category,value,value_header,value_code
0,"classes: edible=e, poisonous=p",class,edible=e,edible,e
0,"classes: edible=e, poisonous=p",class,poisonous=p,poisonous,p
1,"cap-shape: bell=b,conical=c,convex=x,flat=f, k...",cap-shape,bell=b,bell,b
1,"cap-shape: bell=b,conical=c,convex=x,flat=f, k...",cap-shape,conical=c,conical,c
1,"cap-shape: bell=b,conical=c,convex=x,flat=f, k...",cap-shape,convex=x,convex,x

In [27]:
# concating category and value

df_attribute['category-value'] = df_attribute['category'] + ' ' + df_attribute['value_code']

df_attribute.head()

,Field1,category,value,value_header,value_code,category-value
0,"classes: edible=e, poisonous=p",class,edible=e,edible,e,class e
0,"classes: edible=e, poisonous=p",class,poisonous=p,poisonous,p,class p
1,"cap-shape: bell=b,conical=c,convex=x,flat=f, k...",cap-shape,bell=b,bell,b,cap-shape b
1,"cap-shape: bell=b,conical=c,convex=x,flat=f, k...",cap-shape,conical=c,conical,c,cap-shape c
1,"cap-shape: bell=b,conical=c,convex=x,flat=f, k...",cap-shape,convex=x,convex,x,cap-shape x

In [29]:
# mimicing find and replace on category-value from both tables to replace with value_header 

# first, creating dictionary of category-value and value in df_attribute

cat_value_dict = dict(zip(df_attribute['category-value'], df_attribute['value_header']))

cat_value_dict

{'class e': ' edible',
 'class p': ' poisonous',
 'cap-shape b': ' bell',
 'cap-shape c': 'conical',
 'cap-shape x': 'convex',
 'cap-shape f': 'flat',
 'cap-shape k': ' knobbed',
 'cap-shape s': 'sunken',
 'cap-surface f': ' fibrous',
 'cap-surface g': 'grooves',
 'cap-surface y': 'scaly',
 'cap-surface s': 'smooth',
 'cap-color n': ' brown',
 'cap-color b': 'buff',
 'cap-color c': 'cinnamon',
 'cap-color g': 'gray',
 'cap-color r': 'green',
 'cap-color p': 'pink',
 'cap-color u': 'purple',
 'cap-color e': 'red',
 'cap-color w': 'white',
 'cap-color y': 'yellow',
 'bruises t': ' bruises',
 'bruises f': 'no',
 'odor a': ' almond',
 'odor l': 'anise',
 'odor c': 'creosote',
 'odor y': 'fishy',
 'odor f': 'foul',
 'odor m': 'musty',
 'odor n': 'none',
 'odor p': 'pungent',
 'odor s': 'spicy',
 'gill-attachment a': ' attached',
 'gill-attachment d': 'descending',
 'gill-attachment f': 'free',
 'gill-attachment n': 'notched',
 'gill-spacing c': ' close',
 'gill-spacing w': 'crowded',
 'gill-spacing d': 'distant',
 'gill-size b': ' broad',
 'gill-size n': 'narrow',
 'gill-color k': ' black',
 'gill-color n': 'brown',
 'gill-color b': 'buff',
 'gill-color h': 'chocolate',
 'gill-color g': 'gray',
 'gill-color r': ' green',
 'gill-color o': 'orange',
 'gill-color p': 'pink',
 'gill-color u': 'purple',
 'gill-color e': 'red',
 'gill-color w': 'white',
 'gill-color y': 'yellow',
 'stalk-shape e': ' enlarging',
 'stalk-shape t': 'tapering',
 'stalk-root b': ' bulbous',
 'stalk-root c': 'club',
 'stalk-root u': 'cup',
 'stalk-root e': 'equal',
 'stalk-root z': 'rhizomorphs',
 'stalk-root r': 'rooted',
 'stalk-root ?': 'missing',
 'stalk-surface-above-ring f': ' fibrous',
 'stalk-surface-above-ring y': 'scaly',
 'stalk-surface-above-ring k': 'silky',
 'stalk-surface-above-ring s': 'smooth',
 'stalk-surface-below-ring f': ' fibrous',
 'stalk-surface-below-ring y': 'scaly',
 'stalk-surface-below-ring k': 'silky',
 'stalk-surface-below-ring s': 'smooth',
 'stalk-color-above-ring n': ' brown',
 'stalk-color-above-ring b': 'buff',
 'stalk-color-above-ring c': 'cinnamon',
 'stalk-color-above-ring g': 'gray',
 'stalk-color-above-ring o': 'orange',
 'stalk-color-above-ring p': 'pink',
 'stalk-color-above-ring e': 'red',
 'stalk-color-above-ring w': 'white',
 'stalk-color-above-ring y': 'yellow',
 'stalk-color-below-ring n': ' brown',
 'stalk-color-below-ring b': 'buff',
 'stalk-color-below-ring c': 'cinnamon',
 'stalk-color-below-ring g': 'gray',
 'stalk-color-below-ring o': 'orange',
 'stalk-color-below-ring p': 'pink',
 'stalk-color-below-ring e': 'red',
 'stalk-color-below-ring w': 'white',
 'stalk-color-below-ring y': 'yellow',
 'veil-type p': ' partial',
 'veil-type u': 'universal',
 'veil-color n': ' brown',
 'veil-color o': 'orange',
 'veil-color w': 'white',
 'veil-color y': 'yellow',
 'ring-number n': ' none',
 'ring-number o': 'one',
 'ring-number t': 'two',
 'ring-type c': ' cobwebby',
 'ring-type e': 'evanescent',
 'ring-type f': 'flaring',
 'ring-type l': 'large',
 'ring-type n': 'none',
 'ring-type p': 'pendant',
 'ring-type s': 'sheathing',
 'ring-type z': 'zone',
 'spore-print-color k': ' black',
 'spore-print-color n': 'brown',
 'spore-print-color b': 'buff',
 'spore-print-color h': 'chocolate',
 'spore-print-color r': 'green',
 'spore-print-color o': 'orange',
 'spore-print-color u': 'purple',
 'spore-print-color w': 'white',
 'spore-print-color y': 'yellow',
 'population a': ' abundant',
 'population c': 'clustered',
 'population n': 'numerous',
 'population s': 'scattered',
 'population v': 'several',
 'population y': 'solitary',
 'habitat g': ' grasses',
 'habitat l': 'leaves',
 'habitat m': 'meadows',
 'habitat p': 'paths',
 'habitat u': 'urban',
 'habitat w': 'waste',
 'habitat d': 'woods'}

In [35]:
# creating function to replace category-value in df_mushrooms_pivot with value_header

df_mushrooms_pivot = df_mushrooms_pivot.replace(cat_value_dict)

df_mushrooms_pivot.head()

   recordid variable value category-value
0         1    class     p      poisonous
1         2    class     e         edible
2         3    class     e         edible
3         4    class     p      poisonous
4         5    class     e         edible

In [40]:
# crosstabing df_mushrooms

df_final = pd.crosstab(df_mushrooms_pivot['recordid'], df_mushrooms_pivot['variable'], values = df_mushrooms_pivot['category-value'], aggfunc='min')

In [41]:
df_final.head()

variable,bruises,cap-color,cap-shape,cap-surface,class,gill-attachment,gill-color,gill-size,gill-spacing,habitat,...,ring-type,spore-print-color,stalk-color-above-ring,stalk-color-below-ring,stalk-root,stalk-shape,stalk-surface-above-ring,stalk-surface-below-ring,veil-color,veil-type
recordid,,,,,,,,,,,,,,,,,,,,,
1,bruises,brown,convex,smooth,poisonous,free,black,narrow,close,urban,...,pendant,black,white,white,equal,enlarging,smooth,smooth,white,partial
2,bruises,yellow,convex,smooth,edible,free,black,broad,close,grasses,...,pendant,brown,white,white,club,enlarging,smooth,smooth,white,partial
3,bruises,white,bell,smooth,edible,free,brown,broad,close,meadows,...,pendant,brown,white,white,club,enlarging,smooth,smooth,white,partial
4,bruises,white,convex,scaly,poisonous,free,brown,narrow,close,urban,...,pendant,black,white,white,equal,enlarging,smooth,smooth,white,partial
5,no,gray,convex,smooth,edible,free,black,broad,crowded,grasses,...,evanescent,brown,white,white,equal,tapering,smooth,smooth,white,partial