In [37]:
# importing pandas and regex

import pandas as pd
import re

In [3]:
# importing os and grabbing cwd

import os

cwd = os.getcwd()

cwd

'C:\\Users\\CharlesYi\\Jupyter Notebook\\Alteryx Challenges\\Challenge 224_Mushroom for Improvement'

In [5]:
# joining path with file name

path = os.path.join(cwd, 'mushrooms.xlsx')

# grabbing mushroom data

df_mushrooms = pd.read_excel(path)

df_mushrooms.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [7]:
# grabbing attribute data

df_attribute = pd.read_excel(path, sheet_name = 'Sheet2')

df_attribute.head()

                                              Field1
0  Attribute Information: (classes: edible=e, poi...
1  cap-shape: bell=b,conical=c,convex=x,flat=f, k...
2  cap-surface: fibrous=f,grooves=g,scaly=y,smooth=s
3  cap-color: brown=n,buff=b,cinnamon=c,gray=g,gr...
4                            bruises: bruises=t,no=f

In [14]:
# adding record id to mushrooms data

df_mushrooms['recordid'] = range(1, len(df_mushrooms) + 1)

df_mushrooms.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat,recordid
0,p,x,s,n,t,p,f,c,n,k,...,w,w,p,w,o,p,k,s,u,1
1,e,x,s,y,t,a,f,c,b,k,...,w,w,p,w,o,p,n,n,g,2
2,e,b,s,w,t,l,f,c,b,n,...,w,w,p,w,o,p,n,n,m,3
3,p,x,y,w,t,p,f,c,n,n,...,w,w,p,w,o,p,k,s,u,4
4,e,x,s,g,f,n,f,w,b,k,...,w,w,p,w,o,e,n,a,g,5

In [22]:
# transposing

# selecting columns to pivot

pivot_cols = df_mushrooms.columns[0:23]

df_mushrooms_pivot = pd.melt(df_mushrooms, id_vars = ['recordid'], value_vars = pivot_cols)

df_mushrooms_pivot.head()

   recordid variable value
0         1    class     p
1         2    class     e
2         3    class     e
3         4    class     p
4         5    class     e

In [30]:
# concating name and value

df_mushrooms_pivot['category-value'] = df_mushrooms_pivot['variable']+' '+(df_mushrooms_pivot['value'])

df_mushrooms_pivot.head()

   recordid variable value category-value
0         1    class     p        class p
1         2    class     e        class e
2         3    class     e        class e
3         4    class     p        class p
4         5    class     e        class e

In [36]:
# trimming attribute Field1

df_attribute['Field1'] = df_attribute['Field1'].str.strip()

df_attribute.head()

                                              Field1
0  Attribute Information: (classes: edible=e, poi...
1  cap-shape: bell=b,conical=c,convex=x,flat=f, k...
2  cap-surface: fibrous=f,grooves=g,scaly=y,smooth=s
3  cap-color: brown=n,buff=b,cinnamon=c,gray=g,gr...
4                            bruises: bruises=t,no=f

In [41]:
# replacing attribute information in first row 


df_attribute['Field1'] = df_attribute['Field1'].str.replace('Attribute Information: ', '')

df_attribute.head()

                                              Field1
0                   (classes: edible=e, poisonous=p)
1  cap-shape: bell=b,conical=c,convex=x,flat=f, k...
2  cap-surface: fibrous=f,grooves=g,scaly=y,smooth=s
3  cap-color: brown=n,buff=b,cinnamon=c,gray=g,gr...
4                            bruises: bruises=t,no=f

In [77]:
# replacing '(' and ')'

df_attribute['Field1'] = df_attribute['Field1'].apply(lambda x: re.sub(r'[()]', '', x))

df_attribute.head()

                                              Field1
0                     classes: edible=e, poisonous=p
1  cap-shape: bell=b,conical=c,convex=x,flat=f, k...
2  cap-surface: fibrous=f,grooves=g,scaly=y,smooth=s
3  cap-color: brown=n,buff=b,cinnamon=c,gray=g,gr...
4                            bruises: bruises=t,no=f

In [82]:
# splitting field to separate columns

# using just str split func with expand

# df_attribute['Field1'].str.split(r'[:()]+', expand=True)

# using lambda with re.split and pd.Series

df_attribute[['category', 'value']]= df_attribute['Field1'].apply(lambda x: pd.Series(re.split(r'[:]', x)))

df_attribute.head()

,Field1,category,value
0,"classes: edible=e, poisonous=p",classes,"edible=e, poisonous=p"
1,"cap-shape: bell=b,conical=c,convex=x,flat=f, k...",cap-shape,"bell=b,conical=c,convex=x,flat=f, knobbed=k,s..."
2,"cap-surface: fibrous=f,grooves=g,scaly=y,smooth=s",cap-surface,"fibrous=f,grooves=g,scaly=y,smooth=s"
3,"cap-color: brown=n,buff=b,cinnamon=c,gray=g,gr...",cap-color,"brown=n,buff=b,cinnamon=c,gray=g,green=r,pink..."
4,"bruises: bruises=t,no=f",bruises,"bruises=t,no=f"